name: CI/CD Pipeline - Deploy to Server

on:
  push:
    branches: [main]

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 🚀 Notify Discord (Build Started)
        run: |
          curl -H "Content-Type: application/json" \
          -X POST \
          -d '{
            "username": "🚀 Deploy Karibou",
            "embeds": [{
              "title": "🛠 Build in Progress",
              "description": "🔄 `madm-api` is being updated. Grab a coffee ☕ while I work! 🚀",
              "color": 16776960, 
              "fields": [
                { "name": "Branch", "value": "main", "inline": true },
                { "name": "Environment", "value": "Production", "inline": true }
              ]
            }]
          }' \
          ${{ secrets.DISCORD_WEBHOOK_URL }}

      - name: 📥 Checkout Repository
        uses: actions/checkout@v3

      - name: 🔧 Install Dependencies
        run: npm install

      - name: ✅ Run Tests
        run: npm run test

      - name: 🔑 Setup SSH Key (Ed25519)
        run: |
          echo "${{ secrets.SERVER_SSH_KEY }}" > id_ed25519
          chmod 600 id_ed25519
          eval $(ssh-agent -s)
          ssh-add id_ed25519

      - name: 🚀 Deploy to Server via SSH
        run: |
          ssh -i id_ed25519 -o StrictHostKeyChecking=no root@${{ secrets.SERVER_HOST }} <<EOF
          cd ~/madm-api
          git pull origin main

          cd ~/docker
          docker-compose pull
          docker-compose build --no-cache
          docker-compose up -d madm-api
          docker image prune -f
          EOF

      - name: ✅ Notify Discord (Deployment Success)
        if: success()
        run: |
          curl -H "Content-Type: application/json" \
          -X POST \
          -d '{
            "username": "🚀 Deploy Karibou",
            "embeds": [{
              "title": "✅ Deployment Complete",
              "description": "✨ `madm-api` is now live and ready to rock! 🎸🔥",
              "color": 65280, 
              "fields": [
                { "name": "Branch", "value": "main", "inline": true },
                { "name": "Environment", "value": "Production", "inline": true }
              ]
            }]
          }' \
          ${{ secrets.DISCORD_WEBHOOK_URL }}

      - name: ❌ Notify Discord (Deployment Failed)
        if: failure()
        run: |
          curl -H "Content-Type: application/json" \
          -X POST \
          -d '{
            "username": "🚨 Deploy Karibou",
            "embeds": [{
              "title": "❌ Uh-oh! Deployment Failed!",
              "description": "🚨 Something went wrong updating `madm-api`. Check GitHub Actions logs for details.",
              "color": 16711680, 
              "fields": [
                { "name": "Branch", "value": "main", "inline": true },
                { "name": "Environment", "value": "Production", "inline": true }
              ]
            }]
          }' \
          ${{ secrets.DISCORD_WEBHOOK_URL }}
